#!/usr/bin/env python3
"""
Script to export all subject IDs used in the rePLS project.
Extracts subject IDs from CSV data files and saves them to a text file.
"""

import os
import pandas as pd
import glob

def extract_subject_ids_from_csv(csv_path):
    """Extract unique SubjectID values from a CSV file."""
    try:
        df = pd.read_csv(csv_path, usecols=['SubjectID'], low_memory=False)
        subject_ids = df['SubjectID'].unique()
        return set(subject_ids)
    except Exception as e:
        print(f"Error reading {csv_path}: {e}")
        return set()

def main():
    # Data directory
    data_dir = os.path.join(os.path.dirname(__file__), 'data')

    # Collect all subject IDs
    all_subject_ids = set()

    # Check for main data files
    data_files = [
        os.path.join(data_dir, 'ALL_3.csv'),
        os.path.join(data_dir, 'ADNIMERGE.csv'),
    ]

    # Also check for OASIS file (if it exists)
    oasis_file = os.path.join(data_dir, 'oasis_cross-sectional_thickness_combined.csv')
    if os.path.exists(oasis_file):
        data_files.append(oasis_file)

    print("Extracting subject IDs from data files...")

    for csv_file in data_files:
        if os.path.exists(csv_file):
            print(f"Processing: {csv_file}")
            subject_ids = extract_subject_ids_from_csv(csv_file)
            all_subject_ids.update(subject_ids)
            print(f"  Found {len(subject_ids)} unique subject IDs")
        else:
            print(f"File not found: {csv_file}")

    # Sort the subject IDs for consistent output
    sorted_subject_ids = sorted(all_subject_ids)

    # Save to file
    output_file = 'subject_ids_used.txt'
    with open(output_file, 'w') as f:
        f.write("# All subject IDs used in the rePLS project\n")
        f.write("# Extracted from data files in the data/ directory\n")
        f.write(f"# Total unique subjects: {len(sorted_subject_ids)}\n")
        f.write("# Generated by export_subject_ids.py\n\n")
        for subject_id in sorted_subject_ids:
            f.write(f"{subject_id}\n")

    print(f"\nTotal unique subject IDs found: {len(sorted_subject_ids)}")
    print(f"Saved to: {output_file}")

    # Also print some statistics
    print("
Sample subject IDs:")
    for i, sid in enumerate(sorted_subject_ids[:10]):
        print(f"  {sid}")
    if len(sorted_subject_ids) > 10:
        print(f"  ... and {len(sorted_subject_ids) - 10} more")

if __name__ == "__main__":
    main()
